runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_ENV: local   # or production
  APP_DEBUG : true
  APP_LOG: errorlog
  APP_KEY: base64:gLg34YBy+1f3DsonrAnP7kdiNBsAozlsxJLiJ7HDJ10=
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: accred-app
  DB_USERNAME: root
  DB_PASSWORD: Fiawec@2019
  DB_SOCKET: "/cloudsql/lmem-preprod:europe-west1:accred-app"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "lmem-preprod:europe-west1:accred-app"
